<?php

use Illuminate\Database\Seeder;

class EventsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('events')->insert(
            [
                [
                    'id'=>1,
                    'user_id_patient'=>4,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'Sala 22',
                    'request'=>'Consulta médica',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>2,
                    'user_id_patient'=>4,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'Sala 11',
                    'request'=>'Análisis',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>3,
                    'user_id_patient'=>4,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'Rayos',
                    'request'=>'Revisión',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>5,
                    'user_id_patient'=>4,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'Sala 5',
                    'request'=>'Análisis sangre',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s") 
                ],
                [
                    'id'=>9,
                    'user_id_patient'=>4,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>0,
                    'location'=>'666',
                    'request'=>'Revisión vista',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>10,
                    'user_id_patient'=>6,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Revisión final',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>11,
                    'user_id_patient'=>4,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Dolor',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>12,
                    'user_id_patient'=>4,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Revisión nocturna',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s") 
                ],
                [
                    'id'=>13,
                    'user_id_patient'=>4,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Resultados rayos',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>14,
                    'user_id_patient'=>10,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Urgencia revisión médica',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>15,
                    'user_id_patient'=>5,
                    'user_id_doctor'=>11,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'201',
                    'request'=>'Revisión vista',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>16,
                    'user_id_patient'=>5,
                    'user_id_doctor'=>11,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'201',
                    'request'=>'Urgencia máxima',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s") 
                ],
                [
                    'id'=>17,
                    'user_id_patient'=>10,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Revisión',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>18,
                    'user_id_patient'=>10,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Revisión',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>19,
                    'user_id_patient'=>4,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Dar el alta',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>20,
                    'user_id_patient'=>5,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Primera consulta',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s") 
                ],
                [
                    'id'=>21,
                    'user_id_patient'=>10,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Revisión analíticas',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>23,
                    'user_id_patient'=>4,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Urgencia',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>24,
                    'user_id_patient'=>10,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Resultados pruebas',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>25,
                    'user_id_patient'=>4,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Prueba',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s") 
                ],
                [
                    'id'=>26,
                    'user_id_patient'=>4,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Test',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>27,
                    'user_id_patient'=>4,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>0,
                    'location'=>'666',
                    'request'=>'Test',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>28,
                    'user_id_patient'=>4,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Test',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>29,
                    'user_id_patient'=>4,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Pruebas',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s") 
                ],
                [
                    'id'=>30,
                    'user_id_patient'=>4,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>0,
                    'location'=>'666',
                    'request'=>'Revisión final',
                    'finished'=>1,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>31,
                    'user_id_patient'=>10,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Visita urgente',
                    'finished'=>1,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>32,
                    'user_id_patient'=>5,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Dudas',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>33,
                    'user_id_patient'=>10,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s") 
                ],
                [
                    'id'=>34,
                    'user_id_patient'=>10,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Pruebaa',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>35,
                    'user_id_patient'=>4,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Revisión',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>36,
                    'user_id_patient'=>10,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Revisión de analíticas',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>37,
                    'user_id_patient'=>6,
                    'user_id_doctor'=>11,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'201',
                    'request'=>'Evaluación estado salud',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s") 
                ],
                [
                    'id'=>38,
                    'user_id_patient'=>4,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>0,
                    'location'=>'666',
                    'request'=>'Evaluación estado básico',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>39,
                    'user_id_patient'=>4,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Revision',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>40,
                    'user_id_patient'=>4,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Pruebas',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>41,
                    'user_id_patient'=>10,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>0,
                    'location'=>'666',
                    'request'=>'Reconocimento médico',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s") 
                ],
                [
                    'id'=>43,
                    'user_id_patient'=>10,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Pruebas médicas',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>44,
                    'user_id_patient'=>10,
                    'user_id_doctor'=>11,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'201',
                    'request'=>'Revisiones analíticas',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>45,
                    'user_id_patient'=>10,
                    'user_id_doctor'=>11,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'201',
                    'request'=>'Revisión protocolos',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>46,
                    'user_id_patient'=>10,
                    'user_id_doctor'=>11,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'201',
                    'request'=>'Inicio de año',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s") 
                ],
                [
                    'id'=>49,
                    'user_id_patient'=>4,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Prueba agenda',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>50,
                    'user_id_patient'=>10,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'más',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>51,
                    'user_id_patient'=>10,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Más pruebas',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>52,
                    'user_id_patient'=>4,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>0,
                    'location'=>'666',
                    'request'=>'Today',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s") 
                ],
                [
                    'id'=>54,
                    'user_id_patient'=>10,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Vídeo',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>55,
                    'user_id_patient'=>19,
                    'user_id_doctor'=>12,
                    'start'=>0,
                    'online'=>1,
                    'location'=>NULL,
                    'request'=>'Evaluación paciente',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>56,
                    'user_id_patient'=>20,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Pruebas',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>57,
                    'user_id_patient'=>10,
                    'user_id_doctor'=>11,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'201',
                    'request'=>'TEst',
                    'finished'=>0,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s") 
                ],
                [
                    'id'=>58,
                    'user_id_patient'=>10,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'test',
                    'finished'=>1,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>59,
                    'user_id_patient'=>10,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'test',
                    'finished'=>1,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>60,
                    'user_id_patient'=>10,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Evaluación del estado',
                    'finished'=>1,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>61,
                    'user_id_patient'=>10,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Pruebas',
                    'finished'=>1,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s") 
                ],
                [
                    'id'=>66,
                    'user_id_patient'=>10,
                    'user_id_doctor'=>2,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'666',
                    'request'=>'Evaluación estado',
                    'finished'=>1,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
                [
                    'id'=>67,
                    'user_id_patient'=>26,
                    'user_id_doctor'=>25,
                    'start'=>0,
                    'online'=>1,
                    'location'=>'Urgencias',
                    'request'=>'Primera revisión',
                    'finished'=>1,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")
                ],
            ]
        );
    }
}
