<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        DB::table('users')->insert(
            [
                [
                    'id'=>1,
                    'dni'=>'admin',
                    'password'=>'$2y$10$AJ446eQleao9Ti4uzzd.EeCsAA1OZVYQnlb543uAXO6vpjBYrDB7W',
                    'name'=>'Pedro Ramón',
                    'lastname'=>'Moreno Martín',
                    'address'=>'C\ Sin nombre 25',
                    'city'=>'Valdemoro',
                    'country'=>'España',
                    'zipcode'=>'28342',
                    'email'=>'pedroramonmmspam1@gmail.com',
                    'phone'=>'646731068',
                    'birthdate'=>'1990-11-14',
                    'avatar'=>'20200305220349.jpg',
                    'sex'=>'male',
                    'blood'=>'0+',
                    'role_id'=>4,
                    'remember_token'=>'XcfxcZYnEKSBwjpPPSzTnFgX2lQir14EsyWJzmD2OgqnPzEB3CguzRD0dqxG',
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")                  
                ],
                [
                    'id'=>2,
                    'dni'=>'medico',
                    'password'=>'$2y$10$Hbw6QsXSNkn9EqrYTn/hPO0tHIwWaaPGGekWz0Tfg5IXoIJ8doVNq',
                    'name'=>'Juan',
                    'lastname'=>'Chacón Pérez',
                    'address'=>'C\\ Alegria 25',
                    'city'=>'Mostoles',
                    'country'=>'España',
                    'zipcode'=>'28938',
                    'email'=>'juanjuan@juan.es',
                    'phone'=>'666999666',
                    'birthdate'=>'1989-11-01',
                    'avatar'=>NULL,
                    'sex'=>'male',
                    'blood'=>'A+',
                    'role_id'=>2,
                    'remember_token'=>'Y4qikPRD1cDznbUnUO4DkJXSeqAqXt7dUs7VBDgYIAq5zADBu4Map6m0Lgo2',
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")  
                ],
                [
                    'id'=>3,
                    'dni'=>'auxiliar',
                    'password'=>'$2b$10$Im1fAyBSJ6KFLrQ76Agr2eH9FjB7i4alg6VEkJY.x1f4jAwaEN3FS',
                    'name'=>'David',
                    'lastname'=>'Pérez López',
                    'address'=>NULL,
                    'city'=>NULL,
                    'country'=>NULL,
                    'zipcode'=>NULL,
                    'email'=>NULL,
                    'phone'=>NULL,
                    'birthdate'=>'1965-11-25',
                    'avatar'=>NULL,
                    'sex'=>'male',
                    'blood'=>'B-',
                    'role_id'=>3,
                    'remember_token'=>'1x9zcXgkmeqFjemH1UokFSR79NPgG69ozV3V4B32t15nNn7isgHJduZLzjuO',
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")  
                ],
                [
                    'id'=>4,
                    'dni'=>'paciente1',
                    'password'=>'5d772c6e61428f182815b61998f38c7434282a3b',
                    'name'=>'María',
                    'lastname'=>'Márquez Muñoz',
                    'address'=>NULL,
                    'city'=>NULL,
                    'country'=>NULL,
                    'zipcode'=>NULL,
                    'email'=>'maria@test.es',
                    'phone'=>'650210074',
                    'birthdate'=>'1974-10-05',
                    'avatar'=>NULL,
                    'sex'=>'female',
                    'blood'=>'AB+',
                    'role_id'=>1,
                    'remember_token'=>NULL,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")  
                ],
                [
                    'id'=>5,
                    'dni'=>'paciente2',
                    'password'=>'$2b$10$Im1fAyBSJ6KFLrQ76Agr2eH9FjB7i4alg6VEkJY.x1f4jAwaEN3FS',
                    'name'=>'Laura',
                    'lastname'=>'Sánchez Sanz',
                    'address'=>NULL,
                    'city'=>NULL,
                    'country'=>NULL,
                    'zipcode'=>NULL,
                    'email'=>NULL,
                    'phone'=>NULL,
                    'birthdate'=>'1980-01-12',
                    'avatar'=>NULL,
                    'sex'=>'female',
                    'blood'=>'0+',
                    'role_id'=>1,
                    'remember_token'=>NULL,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")  
                ],
                [
                    'id'=>6,
                    'dni'=>'paciente3',
                    'password'=>'5d772c6e61428f182815b61998f38c7434282a3b',
                    'name'=>'Pedro',
                    'lastname'=>'Rodríguez Cano',
                    'address'=>'Calle murcia 55',
                    'city'=>'Mostoles',
                    'country'=>'España',
                    'zipcode'=>'28938',
                    'email'=>'pprr@gmail.com',
                    'phone'=>'666222547',
                    'birthdate'=>'1966-01-20',
                    'avatar'=>NULL,
                    'sex'=>'male',
                    'blood'=>'AB+',
                    'role_id'=>1,
                    'remember_token'=>NULL,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")  
                ],
                [
                    'id'=>10,
                    'dni'=>'47255641L',
                    'password'=>'5d772c6e61428f182815b61998f38c7434282a3b',
                    'name'=>'Marcos',
                    'lastname'=>'Llana Sánchez',
                    'address'=>NULL,
                    'city'=>NULL,
                    'country'=>NULL,
                    'zipcode'=>NULL,
                    'email'=>NULL,
                    'phone'=>NULL,
                    'birthdate'=>'1988-01-05',
                    'avatar'=>NULL,
                    'sex'=>'male',
                    'blood'=>'A-',
                    'role_id'=>1,
                    'remember_token'=>NULL,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")  
                ],
                [
                    'id'=>11,
                    'dni'=>'42215674P',
                    'password'=>'5d772c6e61428f182815b61998f38c7434282a3b',
                    'name'=>'Manuel',
                    'lastname'=>'López Marín',
                    'address'=>NULL,
                    'city'=>NULL,
                    'country'=>NULL,
                    'zipcode'=>NULL,
                    'email'=>NULL,
                    'phone'=>NULL,
                    'birthdate'=>'1980-07-08',
                    'avatar'=>NULL,
                    'sex'=>'male',
                    'blood'=>'B+',
                    'role_id'=>2,
                    'remember_token'=>NULL,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")  
                ],
                [
                    'id'=>12,
                    'dni'=>'25014036L',
                    'password'=>'5d772c6e61428f182815b61998f38c7434282a3b',
                    'name'=>'Sergio',
                    'lastname'=>'Manter Gil',
                    'address'=>NULL,
                    'city'=>NULL,
                    'country'=>NULL,
                    'zipcode'=>NULL,
                    'email'=>NULL,
                    'phone'=>'632444014',
                    'birthdate'=>'1970-03-06',
                    'avatar'=>NULL,
                    'sex'=>'male',
                    'blood'=>'B+',
                    'role_id'=>3,
                    'remember_token'=>NULL,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")  
                ],
                [
                    'id'=>14,
                    'dni'=>'222444888P',
                    'password'=>'5d772c6e61428f182815b61998f38c7434282a3b',
                    'name'=>'Pilar',
                    'lastname'=>'Norto Garrido',
                    'address'=>'Calle propaganda 1',
                    'city'=>'Murcia',
                    'country'=>NULL,
                    'zipcode'=>NULL,
                    'email'=>NULL,
                    'phone'=>NULL,
                    'birthdate'=>'1980-08-16',
                    'avatar'=>NULL,
                    'sex'=>'female',
                    'blood'=>'B-',
                    'role_id'=>2,
                    'remember_token'=>NULL,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")  
                ],
                [
                    'id'=>15,
                    'dni'=>'552654231O',
                    'password'=>'8f15de0b07782d57ca6fda134d8dd9f50f9f0ab5',
                    'name'=>'Santiago',
                    'lastname'=>'Barbas Tones',
                    'address'=>'Calle juan muñoz',
                    'city'=>'Marbella',
                    'country'=>'España',
                    'zipcode'=>'29600',
                    'email'=>'adad@tttttttt.es',
                    'phone'=>'916352001',
                    'birthdate'=>'1979-02-23',
                    'avatar'=>NULL,
                    'sex'=>'male',
                    'blood'=>'0+',
                    'role_id'=>2,
                    'remember_token'=>NULL,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")  
                ],
                [
                    'id'=>16,
                    'dni'=>'33035423T',
                    'password'=>'5d772c6e61428f182815b61998f38c7434282a3b',
                    'name'=>'Tamara',
                    'lastname'=>'Bollo Galdés',
                    'address'=>'Calle pepa',
                    'city'=>NULL,
                    'country'=>NULL,
                    'zipcode'=>NULL,
                    'email'=>NULL,
                    'phone'=>'916551212',
                    'birthdate'=>'1972-04-14',
                    'avatar'=>NULL,
                    'sex'=>'female',
                    'blood'=>'AB+',
                    'role_id'=>2,
                    'remember_token'=>NULL,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")  
                ],
                [
                    'id'=>17,
                    'dni'=>'3684526R',
                    'password'=>'5d772c6e61428f182815b61998f38c7434282a3b',
                    'name'=>'Gloria',
                    'lastname'=>'Carter Gómez',
                    'address'=>NULL,
                    'city'=>NULL,
                    'country'=>NULL,
                    'zipcode'=>NULL,
                    'email'=>'glo@peer.es',
                    'phone'=>'633002450',
                    'birthdate'=>'1959-06-04',
                    'avatar'=>NULL,
                    'sex'=>'female',
                    'blood'=>'A+',
                    'role_id'=>1,
                    'remember_token'=>NULL,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")  
                ],
                [
                    'id'=>18,
                    'dni'=>'33568654J',
                    'password'=>'5d772c6e61428f182815b61998f38c7434282a3b',
                    'name'=>'Carmen',
                    'lastname'=>'Secretaria',
                    'address'=>NULL,
                    'city'=>NULL,
                    'country'=>NULL,
                    'zipcode'=>NULL,
                    'email'=>NULL,
                    'phone'=>NULL,
                    'birthdate'=>'1969-07-03',
                    'avatar'=>NULL,
                    'sex'=>'female',
                    'blood'=>'A-',
                    'role_id'=>3,
                    'remember_token'=>NULL,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")  
                ],
                [
                    'id'=>19,
                    'dni'=>'test',
                    'password'=>'5d772c6e61428f182815b61998f38c7434282a3b',
                    'name'=>'Ruben',
                    'lastname'=>'Martínez Gorúa',
                    'address'=>NULL,
                    'city'=>NULL,
                    'country'=>NULL,
                    'zipcode'=>NULL,
                    'email'=>NULL,
                    'phone'=>NULL,
                    'birthdate'=>'1990-06-14',
                    'avatar'=>NULL,
                    'sex'=>'male',
                    'blood'=>'0+',
                    'role_id'=>1,
                    'remember_token'=>NULL,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")  
                ],
                [
                    'id'=>20,
                    'dni'=>'111111111A',
                    'password'=>'5d772c6e61428f182815b61998f38c7434282a3b',
                    'name'=>'Juan',
                    'lastname'=>'Pérez López',
                    'address'=>NULL,
                    'city'=>NULL,
                    'country'=>NULL,
                    'zipcode'=>NULL,
                    'email'=>NULL,
                    'phone'=>NULL,
                    'birthdate'=>'1989-02-01',
                    'avatar'=>NULL,
                    'sex'=>'male',
                    'blood'=>'A-',
                    'role_id'=>1,
                    'remember_token'=>NULL,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")  
                ],
                [
                    'id'=>21,
                    'dni'=>'222333444A',
                    'password'=>'5d772c6e61428f182815b61998f38c7434282a3b',
                    'name'=>'César',
                    'lastname'=>'Muñoz Cartagena',
                    'address'=>NULL,
                    'city'=>NULL,
                    'country'=>NULL,
                    'zipcode'=>NULL,
                    'email'=>NULL,
                    'phone'=>NULL,
                    'birthdate'=>'1970-03-08',
                    'avatar'=>NULL,
                    'sex'=>'male',
                    'blood'=>'0+',
                    'role_id'=>1,
                    'remember_token'=>NULL,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")  
                ],
                [
                    'id'=>24,
                    'dni'=>'123456A',
                    'password'=>'5d772c6e61428f182815b61998f38c7434282a3b',
                    'name'=>'Ángela',
                    'lastname'=>'Márquez Claro',
                    'address'=>NULL,
                    'city'=>NULL,
                    'country'=>NULL,
                    'zipcode'=>NULL,
                    'email'=>NULL,
                    'phone'=>NULL,
                    'birthdate'=>'1982-05-07',
                    'avatar'=>NULL,
                    'sex'=>'female',
                    'blood'=>'0-',
                    'role_id'=>3,
                    'remember_token'=>NULL,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")  
                ],
                [
                    'id'=>25,
                    'dni'=>'654321A',
                    'password'=>'5d772c6e61428f182815b61998f38c7434282a3b',
                    'name'=>'Francisco',
                    'lastname'=>'Jimeno Torres',
                    'address'=>NULL,
                    'city'=>NULL,
                    'country'=>NULL,
                    'zipcode'=>NULL,
                    'email'=>NULL,
                    'phone'=>NULL,
                    'birthdate'=>'1970-09-10',
                    'avatar'=>NULL,
                    'sex'=>'male',
                    'blood'=>'0+',
                    'role_id'=>2,
                    'remember_token'=>NULL,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")  
                ],
                [
                    'id'=>26,
                    'dni'=>'000000A',
                    'password'=>'5d772c6e61428f182815b61998f38c7434282a3b',
                    'name'=>'Daniel',
                    'lastname'=>'Pérez Martin',
                    'address'=>NULL,
                    'city'=>NULL,
                    'country'=>NULL,
                    'zipcode'=>NULL,
                    'email'=>NULL,
                    'phone'=>NULL,
                    'birthdate'=>'1979-06-08',
                    'avatar'=>NULL,
                    'sex'=>'male',
                    'blood'=>'0+',
                    'role_id'=>1,
                    'remember_token'=>NULL,
                    'created_at'=> date("Y-m-d H:i:s"),
                    'updated_at'=> date("Y-m-d H:i:s")  
                ],
            ]
        );

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

    }
}
